export interface JournalAccountLookup {
  accountNo: string;
  accountName: string;
}

export interface JournalCostCenterLookup {
  centerId: string;
  centerName: string;
}

export interface JournalLine {
  accountNo: string;
  accountName: string;
  debit: number;
  credit: number;
  description?: string | null;
  /** ISO date string OR Date (Date is used in the editing UI; serialized to ISO on save). */
  tranDate: string | Date;
}

export interface JournalEntry {
  tranNo: string;
  /** ISO date string */
  tranDate: string;
  costCenterId: string;
  costCenterName?: string | null;
  lines: JournalLine[];
  /** Computed server-side */
  totalDebit?: number;
  totalCredit?: number;
  balance?: number;
}

export interface JournalListItem {
  tranNo: string;
  /** ISO date string */
  tranDate: string;
  lineCount: number;
  totalDebit: number;
  totalCredit: number;
  costCenterId: string;
  costCenterName?: string | null;
}

export interface JournalListQuery {
  search?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
  page?: number;
  pageSize?: number;
}

export interface PagedJournalResult {
  totalCount: number;
  page: number;
  pageSize: number;
  items: JournalListItem[];
}

export interface JournalNextTranNo {
  tranNo: string;
  autoGenerated: boolean;
}

export interface JournalEntryDialogData {
  /** Prefilled entry when editing; null/undefined for create. */
  entry: JournalEntry | null;
}

export interface JournalEntryDialogResult {
  /** True when the dialog closed because the user saved (success or failure). */
  saved: boolean;
  tranNo?: string;
}