export interface JournalAccountLookup {
  accountNo: string;
  accountName: string;
}

export interface JournalCostCenterLookup {
  centerId: string;
  centerName: string;
}

export interface JournalLine {
  accountNo: string;
  accountName: string;
  debit: number;
  credit: number;
  description?: string | null;
  /** ISO date string OR Date (Date is used in the editing UI; serialized to ISO on save). */
  tranDate: string | Date;
}

export interface JournalEntry {
  tranNo: string;
  /** ISO date string */
  tranDate: string;
  costCenterId: string;
  costCenterName?: string | null;
  lines: JournalLine[];
  /** Computed server-side */
  totalDebit?: number;
  totalCredit?: number;
  balance?: number;
}

export interface JournalListItem {
  tranNo: string;
  /** ISO date string */
  tranDate: string;
  lineCount: number;
  totalDebit: number;
  totalCredit: number;
  costCenterId: string;
  costCenterName?: string | null;
}

export interface JournalListQuery {
  search?: string | null;
  fromDate?: string | null;
  toDate?: string | null;
  page?: number;
  pageSize?: number;
}

export interface PagedJournalResult {
  totalCount: number;
  page: number;
  pageSize: number;
  items: JournalListItem[];
}

/**
 * Flat row from `vwTranx` for the journal-entries-info list grid.
 * One row per journal line, with a running SN and derived Dr/Cr amounts.
 */
export interface JournalListLine {
  sn: number;
  tranDate: string;
  accountName: string;
  accountNo: string;
  debit: number;
  credit: number;
  description?: string | null;
  tranNo: string;
  tranCat?: string | null;
  billNo?: string | null;
  costCenter?: string | null;
  entryDate: string;
  period?: string | null;
  userName?: string | null;
  sNo: number;
  remarks?: string | null;
  coyID: string;
  isClose: boolean;
}

export interface JournalListLineQuery {
  search?: string | null;
  /** ISO date string; when search is empty, restricts to this date. */
  tranDate?: string | null;
  /** ISO date string; used for date-range filtering. */
  fromDate?: string | null;
  /** ISO date string; used for date-range filtering. */
  toDate?: string | null;
  page?: number;
  pageSize?: number;
}

export interface PagedJournalLinesResult {
  totalCount: number;
  page: number;
  pageSize: number;
  items: JournalListLine[];
}

export interface JournalNextTranNo {
  tranNo: string;
  autoGenerated: boolean;
}

export interface JournalEntryDialogData {
  /** Prefilled entry when editing; null/undefined for create. */
  entry: JournalEntry | null;
}

export interface JournalEntryDialogResult {
  /** True when the dialog closed because the user saved (success or failure). */
  saved: boolean;
  tranNo?: string;
}
