using System.ComponentModel.DataAnnotations;

namespace AestheticEMR.Server.ViewModels.Accounting;

public class JournalAccountLookupVM
{
    public string AccountNo { get; set; } = string.Empty;

    public string AccountName { get; set; } = string.Empty;
}

public class JournalCostCenterLookupVM
{
    public string CenterId { get; set; } = string.Empty;

    public string CenterName { get; set; } = string.Empty;
}

public class JournalLineVM
{
    [Required(ErrorMessage = "Account No is required")]
    [StringLength(40)]
    public string AccountNo { get; set; } = string.Empty;

    [Required(ErrorMessage = "Account Name is required")]
    [StringLength(200)]
    public string AccountName { get; set; } = string.Empty;

    [Range(0, double.MaxValue, ErrorMessage = "Debit cannot be negative")]
    public decimal Debit { get; set; }

    [Range(0, double.MaxValue, ErrorMessage = "Credit cannot be negative")]
    public decimal Credit { get; set; }

    [StringLength(500)]
    public string? Description { get; set; }

    [Required(ErrorMessage = "Tran Date is required")]
    public DateTime TranDate { get; set; }
}

public class JournalEntryVM
{
    /// <summary>TranNo - journal transaction number.</summary>
    [Required(ErrorMessage = "Tran No is required")]
    [StringLength(40)]
    public string TranNo { get; set; } = string.Empty;

    [Required(ErrorMessage = "Tran Date is required")]
    public DateTime TranDate { get; set; }

    [Required(ErrorMessage = "Cost Center is required")]
    [StringLength(40)]
    public string CostCenterId { get; set; } = string.Empty;

    public string? CostCenterName { get; set; }

    [Required(ErrorMessage = "At least one journal line is required")]
    [MinLength(1, ErrorMessage = "At least one journal line is required")]
    public List<JournalLineVM> Lines { get; set; } = new();

    public decimal TotalDebit => Lines?.Sum(l => l.Debit) ?? 0m;

    public decimal TotalCredit => Lines?.Sum(l => l.Credit) ?? 0m;

    public decimal Balance => Math.Abs(TotalDebit - TotalCredit);
}

public class JournalListItemVM
{
    public string TranNo { get; set; } = string.Empty;

    public DateTime TranDate { get; set; }

    public int LineCount { get; set; }

    public decimal TotalDebit { get; set; }

    public decimal TotalCredit { get; set; }

    public string CostCenterId { get; set; } = string.Empty;

    public string? CostCenterName { get; set; }
}

public class JournalListQueryVM
{
    [StringLength(40)]
    public string? Search { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    [Range(1, int.MaxValue)]
    public int Page { get; set; } = 1;

    [Range(1, 200)]
    public int PageSize { get; set; } = 10;
}

public class PagedJournalResultVM
{
    public int TotalCount { get; set; }

    public int Page { get; set; }

    public int PageSize { get; set; }

    public List<JournalListItemVM> Items { get; set; } = new();
}

public class JournalNextTranNoVM
{
    public string TranNo { get; set; } = string.Empty;

    public bool AutoGenerated { get; set; }
}