import { Component, OnInit, TemplateRef, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse, HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { NgbModal, NgbModalRef } from '@ng-bootstrap/ng-bootstrap';

import { fadeInOut } from '../../../services/animations';
import { AlertService, DialogType, MessageSeverity } from '../../../services/alert.service';
import { HPatientEndpoint } from '../../../services/h-patient-endpoint.service';
import { HRetainershipEndpoint } from '../../../services/h-retainership-endpoint.service';
import { HPatient } from '../../../models/legacy/h-patient.model';
import { HRetainership } from '../../../models/legacy/h-retainership.model';

interface FrontdeskSettings {
  clientType?: Record<string, string[]>;
}

@Component({
  selector: 'app-patients',
  templateUrl: './patients.component.html',
  styleUrl: './patients.component.scss',
  animations: [fadeInOut],
  imports: [CommonModule, ReactiveFormsModule, FormsModule, TranslateModule]
})
export class PatientsComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly alertService = inject(AlertService);
  private readonly patientEndpoint = inject(HPatientEndpoint);
  private readonly retainershipEndpoint = inject(HRetainershipEndpoint);
  private readonly router = inject(Router);
  private readonly modalService = inject(NgbModal);
  private readonly http = inject(HttpClient);

  patients: HPatient[] = [];
  patientsCache: HPatient[] = [];
  filteredPatients: HPatient[] = [];
  companies: HRetainership[] = [];
  frontdeskSettings: FrontdeskSettings | null = null;
  patCatOptions: string[] = [];
  searchText = '';
  loadingIndicator = false;
  isEditing = false;
  currentPatient: HPatient | null = null;
  modalRef: NgbModalRef | null = null;

  // Photo state
  photoPreview: string | null = null;
  photoBase64: string | null = null;
  viewingPhotoPatient: HPatient | null = null;

  readonly patientCategoryOptions = ['HMO', 'PRIVATE', 'MTHLY', 'NHIS'];
  readonly maritalStatuses = ['SINGLE', 'MARRIED'];
  readonly sexOptions = ['MALE', 'FEMALE'];
  readonly pageSize = 10;
  currentPage = 1;

  patientForm = this.fb.group({
    // pno is auto-generated by the server (getIDNo stored proc) — hidden in UI
    pno: [{ value: '', disabled: true }],
    oldPno: ['', Validators.maxLength(100)],
    pSurName: ['', [Validators.required, Validators.maxLength(255)]],
    pFirstname: ['', Validators.maxLength(150)],
    title: ['', Validators.maxLength(150)],
    sex: ['', Validators.maxLength(50)],
    mstatus: ['', Validators.maxLength(100)],
    dob: [''],
    occupation: ['', Validators.maxLength(100)],
    homeAddress: ['', Validators.maxLength(1100)],
    officeAddress: ['', Validators.maxLength(1000)],
    pPhoneNo: ['', Validators.maxLength(100)],
    email: ['', Validators.maxLength(500)],
    empNo: ['', Validators.maxLength(100)],
    nextofKin: ['', Validators.maxLength(500)],
    kinAddress: ['', Validators.maxLength(1000)],
    relationToKin: ['', Validators.maxLength(100)],
    pCatId: ['', Validators.maxLength(100)],
    coyName: ['', Validators.maxLength(7)],
    clientCatId: ['', Validators.maxLength(100)],
    policyType: ['', Validators.maxLength(100)],
    nokphone: ['', Validators.maxLength(100)],
    regDate: [this.getTodayInputValue()],
    userName: ['', Validators.maxLength(100)]
  });

  ngOnInit(): void {
    this.loadFrontdeskSettings();
    this.loadData();
    this.loadCompanies();
    // Listen for company selection changes
    this.patientForm.get('coyName')?.valueChanges.subscribe(val => {
      this.updatePatCatOptions(val ?? '');
    });
  }

  loadFrontdeskSettings(): void {
    this.http.get<FrontdeskSettings>('/assets/module-settings/frontdesk.json').subscribe({
      next: settings => {
        this.frontdeskSettings = settings;
        // Set default options on load
        this.updatePatCatOptions((this.patientForm.get('coyName')?.value ?? ''));
      },
      error: () => {
        this.frontdeskSettings = null;
        this.patCatOptions = ['PRIVATE', 'MTHLY', 'HMO', 'NHIS'];
      }
    });
  }

  updatePatCatOptions(selectedCompanyId: string): void {
    if (!this.frontdeskSettings || !this.frontdeskSettings.clientType) {
      this.patCatOptions = ['PRIVATE', 'MTHLY', 'HMO', 'NHIS'];
      return;
    }
    let clientType = '';
    if (selectedCompanyId) {
      const company = this.companies.find(c => c.retainId === selectedCompanyId);
      clientType = company?.clientType || '';
    }
    let options: string[] = [];
    if (clientType && this.frontdeskSettings.clientType[clientType]) {
      options = this.frontdeskSettings.clientType[clientType];
    } else if (this.frontdeskSettings.clientType['default']) {
      options = this.frontdeskSettings.clientType['default'];
    } else {
      options = ['PRIVATE', 'MTHLY', 'HMO', 'NHIS'];
    }
    this.patCatOptions = options;
    // Optionally reset patient category if not in new list
    const currentCat = this.patientForm.get('clientCatId')?.value ?? '';
    if (!options.includes(currentCat)) {
      this.patientForm.get('clientCatId')?.setValue('');
    }
  }

  get filteredCompanies(): HRetainership[] {
    return this.companies;
  }

  get totalPages(): number {
    return Math.max(1, Math.ceil(this.filteredPatients.length / this.pageSize));
  }

  get pagedPatients(): HPatient[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredPatients.slice(start, start + this.pageSize);
  }

  goToPage(page: number): void {
    if (page < 1 || page > this.totalPages) {
      return;
    }

    this.currentPage = page;
  }

  loadCompanies(): void {
    this.retainershipEndpoint.getHRetainershipsEndpoint<HRetainership[] | { $values?: unknown[]; items?: unknown[]; data?: unknown[] }>()
      .subscribe({
        next: response => {
          this.companies = this.extractCompanies(response)
            .sort((a, b) => (a.retainName ?? '').localeCompare(b.retainName ?? ''));
        },
        error: () => {
          this.companies = [];
        }
      });
  }

  loadData(): void {
    this.alertService.startLoadingMessage();
    this.loadingIndicator = true;

    this.patientEndpoint.getHPatientsEndpoint<HPatient[]>()
      .subscribe({
        next: patients => {
          this.alertService.stopLoadingMessage();
          this.loadingIndicator = false;
          this.patients = patients;
          this.patientsCache = [...patients];
          this.onSearch();
        },
        error: error => {
          this.alertService.stopLoadingMessage();
          this.loadingIndicator = false;
          this.alertService.showStickyMessage(
            'Load Error',
            `Unable to retrieve patients.\r\nError: "${this.getErrorMessage(error)}"`,   MessageSeverity.error,
            error
          );
        }
      });
  }

  openCreate(content: TemplateRef<unknown>): void {
    this.isEditing = false;
    this.currentPatient = null;
    this.photoPreview = null;
    this.photoBase64 = null;
    this.patientForm.reset({
      regDate: this.getTodayInputValue()
    });

    if (!this.companies.length) {
      this.loadCompanies();
    }

    this.modalRef = this.modalService.open(content, { size: 'xl', scrollable: true, backdrop: 'static', keyboard: false });
  }

  openEdit(content: TemplateRef<unknown>, patient: HPatient): void {
    this.isEditing = true;
    this.currentPatient = patient;
    this.photoBase64 = null;
    // Show existing photo from server if available
    this.photoPreview = patient.patPixBase64
      ? (patient.patPixBase64.startsWith('data:') ? patient.patPixBase64 : `data:image/jpeg;base64,${patient.patPixBase64}`)
      : null;

    this.patientForm.patchValue({
      ...patient,
      dob: this.toDateInputValue(patient.dob),
      regDate: this.toDateInputValue(patient.regDate) || this.getTodayInputValue()
    });

    if (!this.companies.length) {
      this.loadCompanies();
    }

    this.modalRef = this.modalService.open(content, { size: 'xl', scrollable: true, backdrop: 'static', keyboard: false });
  }

  cancelForm(): void {
    this.currentPatient = null;
    this.photoPreview = null;
    this.photoBase64 = null;
    this.patientForm.reset({
      regDate: this.getTodayInputValue()
    });
    this.modalRef?.close();
    this.modalRef = null;
  }

  onPhotoSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      this.photoPreview = result;
      this.photoBase64 = result; // full data URI e.g. "data:image/jpeg;base64,..."
    };
    reader.readAsDataURL(file);
  }

  removePhoto(): void {
    this.photoPreview = null;
    this.photoBase64 = null;
  }

  savePatient(): void {
    if (this.patientForm.invalid) {
      this.alertService.showStickyMessage('Validation Error', 'Please correct the form errors.', MessageSeverity.error);
      return;
    }

    const raw = this.patientForm.getRawValue();

    this.alertService.startLoadingMessage();

    if (this.isEditing && this.currentPatient) {
      const payload: HPatient = {
        ...raw,
        pno: this.currentPatient.pno,
        patPixBase64: this.photoBase64 ?? undefined
      } as HPatient;
      this.patientEndpoint.getUpdateHPatientEndpoint<HPatient>(this.currentPatient.pno!, payload)
        .subscribe({
          next: updated => {
            this.alertService.stopLoadingMessage();
            const index = this.patients.findIndex(x => x.pno === updated.pno);
            if (index > -1) {
              this.patients[index] = updated;
              this.patientsCache = [...this.patients];
              this.onSearch();
            }
            this.cancelForm();
            this.alertService.showMessage('Success', 'Patient updated successfully.', MessageSeverity.success);
          },
          error: error => {
            this.alertService.stopLoadingMessage();
            this.alertService.showStickyMessage(
              'Update Error',
              `Unable to update patient.\r\nError: "${this.getErrorMessage(error)}"`,    MessageSeverity.error,
              error
            );
          }
        });
      return;
    }

    const { pno, ...createPayload } = raw as HPatient;
    void pno;
    const newPatient: HPatient = {
      ...createPayload,
      patPixBase64: this.photoBase64 ?? undefined
    } as HPatient;
    this.patientEndpoint.getNewHPatientEndpoint<HPatient>(newPatient)
      .subscribe({
        next: created => {
          this.alertService.stopLoadingMessage();
          this.patients.push(created);
          this.patientsCache = [...this.patients];
          this.onSearch();
          this.cancelForm();
          this.alertService.showMessage('Success', 'Patient created successfully.', MessageSeverity.success);
        },
        error: error => {
          this.alertService.stopLoadingMessage();
          this.alertService.showStickyMessage(
            'Create Error',
            `Unable to create patient.\r\nError: "${this.getErrorMessage(error)}"`,    MessageSeverity.error,
            error
          );
        }
      });
  }

  deletePatient(patient: HPatient): void {
    this.alertService.showDialog('Are you sure you want to delete this patient?', DialogType.confirm,
      () => {
        this.alertService.startLoadingMessage();
        this.patientEndpoint.getDeleteHPatientEndpoint<void>(patient.pno!)
          .subscribe({
            next: () => {
              this.alertService.stopLoadingMessage();
              this.patients = this.patients.filter(x => x.pno !== patient.pno);
              this.patientsCache = [...this.patients];
              this.onSearch();
              this.alertService.showMessage('Success', 'Patient deleted successfully.', MessageSeverity.success);
            },
            error: error => {
              this.alertService.stopLoadingMessage();
              const message = this.getErrorMessage(error);
              this.alertService.showStickyMessage(
                'Delete Error',
                message.includes('attendance records')
                  ? 'Cannot delete this patient because related attendance records exist.'
                  : `Unable to delete patient.\r\nError: "${message}"`,
                MessageSeverity.error,
                error
              );
            }
          });
      });
  }

  onSearch(): void {
    const term = this.searchText.trim().toLowerCase();

    if (!term) {
      this.filteredPatients = this.patientsCache.filter(x => this.isToday(x.regDate));
      this.currentPage = 1;
      return;
    }

    this.filteredPatients = this.patientsCache.filter(x =>
      (x.pno ?? '').toLowerCase().includes(term)
      || (x.pSurName ?? '').toLowerCase().includes(term)
      || (x.pFirstname ?? '').toLowerCase().includes(term)
      || (x.coyName ?? '').toLowerCase().includes(term)
      || (x.pPhoneNo ?? '').toLowerCase().includes(term)
      || (x.email ?? '').toLowerCase().includes(term)
    );

    this.currentPage = 1;
  }

  openAttendanceForPatient(patient: HPatient): void {
    if (!patient.pno) {
      return;
    }

    void this.router.navigate(['/frontdesk/attendance'], {
      queryParams: { action: 'create', pNo: patient.pno }
    });
  }

  openAppointmentForPatient(patient: HPatient): void {
    if (!patient.pno) {
      return;
    }

    void this.router.navigate(['/frontdesk/appointments'], {
      queryParams: { action: 'create', pNo: patient.pno }
    });
  }

  viewPhoto(content: TemplateRef<unknown>, patient: HPatient): void {
    this.viewingPhotoPatient = patient;
    this.modalService.open(content, { size: 'sm', centered: true, backdrop: 'static', keyboard: false });
  }

  getPhotoSrc(patient: HPatient): string {
    const b64 = patient.patPixBase64 ?? '';
    return b64.startsWith('data:') ? b64 : `data:image/jpeg;base64,${b64}`;
  }

  private extractCompanies(
    response: HRetainership[] | { $values?: unknown[]; items?: unknown[]; data?: unknown[] } | null | undefined
  ): HRetainership[] {
    const items = Array.isArray(response)
      ? response
      : Array.isArray(response?.$values)
        ? response.$values
        : Array.isArray(response?.items)
          ? response.items
          : Array.isArray(response?.data)
            ? response.data
            : [];

    return items.map(item => this.normalizeRetainership(item));
  }

  private normalizeRetainership(item: unknown): HRetainership {
    const source = item as Partial<HRetainership> & Record<string, unknown>;

    const getString = (camelKey: keyof HRetainership, pascalKey: string): string | undefined => {
      const camelValue = source[camelKey as string];
      if (typeof camelValue === 'string') {
        return camelValue;
      }

      const pascalValue = source[pascalKey];
      if (typeof pascalValue === 'string') {
        return pascalValue;
      }

      return undefined;
    };

    return {
      retainId: getString('retainId', 'RetainId') ?? '',
      retainCode: getString('retainCode', 'RetainCode') ?? '',
      retainName: getString('retainName', 'RetainName') ?? '',
      clientCatId: getString('clientCatId', 'ClientCatId'),
      clientType: getString('clientType', 'ClientType'),
      address: getString('address', 'Address'),
      phoneNo: getString('phoneNo', 'PhoneNo'),
      email: getString('email', 'Email'),
      contact: getString('contact', 'Contact'),
      active: getString('active', 'Active')
    };
  }

  private toDateInputValue(value?: string | null): string {
    if (!value) {
      return '';
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return '';
    }

    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  private getErrorMessage(error: unknown): string {
    if (error instanceof HttpErrorResponse) {
      const payload = error.error as { message?: string; [key: string]: unknown } | undefined;
      const directMessage = payload?.message;
      if (directMessage) {
        return directMessage;
      }

      if (payload && typeof payload === 'object') {
        for (const value of Object.values(payload)) {
          if (Array.isArray(value) && value.length && typeof value[0] === 'string') {
            return value[0];
          }
        }
      }

      return error.message;
    }

    return (error as Error)?.message || 'Unknown error';
  }

  private getTodayInputValue(): string {
    return new Date().toISOString().split('T')[0];
  }

  private isToday(value?: string | null): boolean {
    if (!value) {
      return false;
    }

    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return false;
    }

    const today = new Date();
    return date.getFullYear() === today.getFullYear()
      && date.getMonth() === today.getMonth()
      && date.getDate() === today.getDate();
  }
}
