using AestheticEMR.Core.Services.Accounting.Interfaces;
using AestheticEMR.Core.Services.Accounting.Models;
using AestheticEMR.Server.Authorization;
using AestheticEMR.Server.ViewModels.Accounting;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AestheticEMR.Server.Controllers.Accounting;

[Route("api/accounting/journal")]
[ApiController]
[Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
public class JournalController(
    IJournalEntryService journalEntryService,
    ILogger<JournalController> logger,
    IMapper mapper) : BaseApiController(logger, mapper)
{
    [HttpGet]
    [ProducesResponseType(typeof(PagedJournalResultVM), 200)]
    public async Task<IActionResult> GetPaged([FromQuery] JournalListQueryVM query, CancellationToken ct)
    {
        try
        {
            var coreQuery = _mapper.Map<JournalListQuery>(query);
            var result = await journalEntryService.GetPagedAsync(coreQuery, ct);
            return Ok(_mapper.Map<PagedJournalResultVM>(result));
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error retrieving journal entries");
            AddModelError("Unable to retrieve journal entries");
            return BadRequest(ModelState);
        }
    }

    [HttpGet("{tranNo}")]
    [ProducesResponseType(typeof(JournalEntryVM), 200)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetByTranNo(string tranNo, CancellationToken ct)
    {
        try
        {
            var entry = await journalEntryService.GetByTranNoAsync(tranNo, ct);
            if (entry is null)
            {
                return NotFound(tranNo);
            }
            return Ok(_mapper.Map<JournalEntryVM>(entry));
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error retrieving journal entry {TranNo}", tranNo);
            AddModelError("Unable to retrieve journal entry");
            return BadRequest(ModelState);
        }
    }

    [HttpGet("next-tran-no")]
    [ProducesResponseType(typeof(JournalNextTranNoVM), 200)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> GetNextTranNo(CancellationToken ct)
    {
        try
        {
            var tranNo = await journalEntryService.GenerateNextTranNoAsync(ct);
            return Ok(new JournalNextTranNoVM
            {
                TranNo = tranNo,
                AutoGenerated = true
            });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error generating next journal tran-no");
            AddModelError("Unable to generate next transaction number");
            return BadRequest(ModelState);
        }
    }

    [HttpGet("accounts")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetAccounts(CancellationToken ct)
    {
        try
        {
            var accounts = await journalEntryService.GetAccountsAsync(ct);
            return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error retrieving chart of accounts");
            AddModelError("Unable to retrieve chart of accounts");
            return BadRequest(ModelState);
        }
    }

    [HttpGet("cost-centers")]
    [ProducesResponseType(typeof(IEnumerable<JournalCostCenterLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetCostCenters(CancellationToken ct)
    {
        try
        {
            var costCenters = await journalEntryService.GetCostCentersAsync(ct);
            return Ok(_mapper.Map<IEnumerable<JournalCostCenterLookupVM>>(costCenters));
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error retrieving cost centers");
            AddModelError("Unable to retrieve cost centers");
            return BadRequest(ModelState);
        }
    }

    [HttpPost]
    [ProducesResponseType(typeof(JournalEntryVM), 201)]
    [ProducesResponseType(400)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Create([FromBody] JournalEntryVM model, CancellationToken ct)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            var currentUser = GetCurrentUserId();
            var coreEntry = _mapper.Map<JournalEntry>(model);
            var created = await journalEntryService.CreateAsync(coreEntry, currentUser, ct);
            return CreatedAtAction(nameof(GetByTranNo), new { tranNo = created.TranNo }, _mapper.Map<JournalEntryVM>(created));
        }
        catch (InvalidOperationException ex)
        {
            logger.LogWarning(ex, "Validation error creating journal entry");
            AddModelError(ex.Message);
            return BadRequest(ModelState);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error creating journal entry {TranNo}", model.TranNo);
            AddModelError("Unable to save journal entry");
            return BadRequest(ModelState);
        }
    }

    [HttpPut("{tranNo}")]
    [ProducesResponseType(typeof(JournalEntryVM), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Update(string tranNo, [FromBody] JournalEntryVM model, CancellationToken ct)
    {
        if (!string.Equals(tranNo, model.TranNo, StringComparison.OrdinalIgnoreCase))
        {
            AddModelError("TranNo in URL does not match body");
            return BadRequest(ModelState);
        }

        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            var currentUser = GetCurrentUserId();
            var existing = await journalEntryService.GetByTranNoAsync(tranNo, ct);
            if (existing is null)
            {
                return NotFound(tranNo);
            }

            var coreEntry = _mapper.Map<JournalEntry>(model);
            var updated = await journalEntryService.UpdateAsync(coreEntry, currentUser, ct);
            return Ok(_mapper.Map<JournalEntryVM>(updated));
        }
        catch (InvalidOperationException ex)
        {
            logger.LogWarning(ex, "Validation error updating journal entry {TranNo}", tranNo);
            AddModelError(ex.Message);
            return BadRequest(ModelState);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error updating journal entry {TranNo}", tranNo);
            AddModelError("Unable to update journal entry");
            return BadRequest(ModelState);
        }
    }

    [HttpDelete("{tranNo}")]
    [ProducesResponseType(204)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Delete(string tranNo, CancellationToken ct)
    {
        try
        {
            var currentUser = GetCurrentUserId();
            var existing = await journalEntryService.GetByTranNoAsync(tranNo, ct);
            if (existing is null)
            {
                return NotFound(tranNo);
            }

            await journalEntryService.DeleteAsync(tranNo, currentUser, ct);
            return NoContent();
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error deleting journal entry {TranNo}", tranNo);
            AddModelError("Unable to delete journal entry");
            return BadRequest(ModelState);
        }
    }
}