using AestheticEMR.Core.Services.Accounting.Interfaces;
using AestheticEMR.Core.Services.Accounting.Models;
using AestheticEMR.Server.Authorization;
using AestheticEMR.Server.ViewModels.Accounting;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AestheticEMR.Server.Controllers.Accounting;

/// <summary>
/// Controller for journal entries (manual journal vouchers).
///
/// Error-handling policy: only <see cref="InvalidOperationException"/> and
/// <see cref="ArgumentException"/> are mapped to 400 — they carry domain
/// validation messages meant for the caller. Everything else bubbles up to
/// the framework so the real exception (AutoMapper, Dapper, SQL, etc.)
/// shows up in the log with a stack trace instead of being swallowed into
/// a useless "Unable to …" 400.
/// </summary>
[Route("api/accounting/journal")]
[ApiController]
[Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
public class JournalController(
    IJournalEntryService journalEntryService,
    ILogger<JournalController> logger,
    IMapper mapper) : BaseApiController(logger, mapper)
{
    [HttpGet]
    [ProducesResponseType(typeof(PagedJournalResultVM), 200)]
    public async Task<IActionResult> GetPaged([FromQuery] JournalListQueryVM query, CancellationToken ct)
    {
        var coreQuery = _mapper.Map<JournalListQuery>(query);
        var result = await journalEntryService.GetPagedAsync(coreQuery, ct);
        return Ok(_mapper.Map<PagedJournalResultVM>(result));
    }

    /// <summary>
    /// Flat line-level list backed by <c>vwTranx</c>. Used by the
    /// journal-entries-info list grid: one row per journal line, with a
    /// running SN, derived Dr/Cr amounts, and the underlying view's
    /// metadata (TranCat, BillNo, CostCenter, Period, UserName, etc.).
    /// </summary>
    [HttpGet("lines")]
    [ProducesResponseType(typeof(PagedJournalLinesResultVM), 200)]
    public async Task<IActionResult> GetPagedLines([FromQuery] JournalListLineQueryVM query, CancellationToken ct)
    {
        var coreQuery = _mapper.Map<JournalListLineQuery>(query);
        var result = await journalEntryService.GetPagedLinesAsync(coreQuery, ct);
        return Ok(_mapper.Map<PagedJournalLinesResultVM>(result));
    }

    [HttpGet("{tranNo}")]
    [ProducesResponseType(typeof(JournalEntryVM), 200)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetByTranNo(string tranNo, CancellationToken ct)
    {
        var entry = await journalEntryService.GetByTranNoAsync(tranNo, ct);
        if (entry is null)
        {
            return NotFound(new { tranNo });
        }
        return Ok(_mapper.Map<JournalEntryVM>(entry));
    }

    [HttpGet("next-tran-no")]
    [ProducesResponseType(typeof(JournalNextTranNoVM), 200)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> GetNextTranNo(CancellationToken ct)
    {
        var tranNo = await journalEntryService.GenerateNextTranNoAsync(ct);
        return Ok(new JournalNextTranNoVM
        {
            TranNo = tranNo,
            AutoGenerated = true
        });
    }

    [HttpGet("accounts")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/debtors/debit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetDebtorDebitAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetDebtorDebitAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/debtors/credit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetDebtorCreditAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetDebtorCreditAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/creditors/debit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetCreditorDebitAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetCreditorDebitAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/creditors/credit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetCreditorCreditAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetCreditorCreditAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/purchases/debit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetPurchasesDebitAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetPurchasesDebitAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("accounts/purchases/credit")]
    [ProducesResponseType(typeof(IEnumerable<JournalAccountLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetPurchasesCreditAccounts(CancellationToken ct)
    {
        var accounts = await journalEntryService.GetPurchasesCreditAccountsAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalAccountLookupVM>>(accounts));
    }

    [HttpGet("cost-centers")]
    [ProducesResponseType(typeof(IEnumerable<JournalCostCenterLookupVM>), 200)]
    [Authorize(Policy = AuthPolicies.ViewAccountingPolicy)]
    public async Task<IActionResult> GetCostCenters(CancellationToken ct)
    {
        var costCenters = await journalEntryService.GetCostCentersAsync(ct);
        return Ok(_mapper.Map<IEnumerable<JournalCostCenterLookupVM>>(costCenters));
    }

    [HttpPost]
    [ProducesResponseType(typeof(JournalEntryVM), 201)]
    [ProducesResponseType(400)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Create([FromBody] JournalEntryVM model, CancellationToken ct)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(new ValidationProblemDetails(ModelState));
        }

        try
        {
            var currentUser = GetCurrentUserId();
            var coreEntry = _mapper.Map<JournalEntry>(model);
            var created = await journalEntryService.CreateAsync(coreEntry, currentUser, ct);
            return CreatedAtAction(nameof(GetByTranNo), new { tranNo = created.TranNo }, _mapper.Map<JournalEntryVM>(created));
        }
        catch (InvalidOperationException ex)
        {
            logger.LogWarning(ex, "Validation error creating journal entry");
            AddModelError(ex.Message);
            return BadRequest(new ValidationProblemDetails(ModelState));
        }
    }

    [HttpPut("{tranNo}")]
    [ProducesResponseType(typeof(JournalEntryVM), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Update(string tranNo, [FromBody] JournalEntryVM model, CancellationToken ct)
    {
        if (!string.Equals(tranNo, model.TranNo, StringComparison.OrdinalIgnoreCase))
        {
            AddModelError("TranNo in URL does not match body");
            return BadRequest(new ValidationProblemDetails(ModelState));
        }

        if (!ModelState.IsValid)
        {
            return BadRequest(new ValidationProblemDetails(ModelState));
        }

        try
        {
            var currentUser = GetCurrentUserId();
            var existing = await journalEntryService.GetByTranNoAsync(tranNo, ct);
            if (existing is null)
            {
                return NotFound(new { tranNo });
            }

            var coreEntry = _mapper.Map<JournalEntry>(model);
            var updated = await journalEntryService.UpdateAsync(coreEntry, currentUser, ct);
            return Ok(_mapper.Map<JournalEntryVM>(updated));
        }
        catch (InvalidOperationException ex)
        {
            logger.LogWarning(ex, "Validation error updating journal entry {TranNo}", tranNo);
            AddModelError(ex.Message);
            return BadRequest(new ValidationProblemDetails(ModelState));
        }
    }

    [HttpDelete("{tranNo}")]
    [ProducesResponseType(204)]
    [ProducesResponseType(404)]
    [Authorize(Policy = AuthPolicies.ManageAccountingPolicy)]
    public async Task<IActionResult> Delete(string tranNo, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(tranNo))
        {
            AddModelError("TranNo is required");
            return BadRequest(new ValidationProblemDetails(ModelState));
        }

        var currentUser = GetCurrentUserId();
        var existing = await journalEntryService.GetByTranNoAsync(tranNo, ct);
        if (existing is null)
        {
            return NotFound(new { tranNo });
        }

        await journalEntryService.DeleteAsync(tranNo, currentUser, ct);
        return NoContent();
    }
}