export interface HPatient {
  pno?: string;   // auto-generated by server — not sent on create
  oldPno?: string;
  pSurName: string;
  pFirstname?: string;
  title?: string;
  sex?: string;
  mstatus?: string;
  dob?: string;
  occupation?: string;
  homeAddress?: string;
  officeAddress?: string;
  pPhoneNo?: string;
  email?: string;
  empNo?: string;
  branch?: string;
  nextofKin?: string;
  kinAddress?: string;
  relationToKin?: string;
  pCatId?: string;
  coyType?: string;
  coyName?: string; // Company
  clientCatId?: string;
  cardType?: string;
  policyType?: string;
  nokphone?: string;
  status?: string;
  regDate?: string;
  userName?: string;
}
