using System.ComponentModel.DataAnnotations;

namespace AestheticEMR.Server.ViewModels.Legacy;

public class HPatientVM
{
    // Auto-generated by stored proc getIDNo — read-only, not required on create
    public string? Pno { get; set; }

    [StringLength(100)]
    public string? OldPno { get; set; }

    [Required]
    [StringLength(255)]
    public string PSurName { get; set; } = null!;

    [StringLength(150)]
    public string? PFirstname { get; set; }

    [StringLength(150)]
    public string? Title { get; set; }

    [StringLength(50)]
    public string? Sex { get; set; }

    [StringLength(100)]
    public string? Mstatus { get; set; }

    public DateTime? Dob { get; set; }

    [StringLength(100)]
    public string? Occupation { get; set; }

    [StringLength(1100)]
    public string? HomeAddress { get; set; }

    [StringLength(1000)]
    public string? OfficeAddress { get; set; }

    [StringLength(100)]
    public string? PPhoneNo { get; set; }

    [StringLength(500)]
    public string? Email { get; set; }

    [StringLength(100)]
    public string? EmpNo { get; set; }

    [StringLength(100)]
    public string? Branch { get; set; }

    [StringLength(500)]
    public string? NextofKin { get; set; }

    [StringLength(1000)]
    public string? KinAddress { get; set; }

    [StringLength(100)]
    public string? RelationToKin { get; set; }

    [StringLength(100)]
    public string? PCatId { get; set; }

    [StringLength(100)]
    public string? CoyType { get; set; }

    [StringLength(7)]
    public string? CoyName { get; set; }

    [StringLength(255)]
    public string? ClientName { get; set; }

    [StringLength(100)]
    public string? ClientCatId { get; set; }

    [StringLength(100)]
    public string? CardType { get; set; }

    [StringLength(100)]
    public string? PolicyType { get; set; }

    [StringLength(100)]
    public string? Nokphone { get; set; }

    [StringLength(100)]
    public string? Status { get; set; }

    [Range(0, (double)decimal.MaxValue)]
    public decimal? DebtBf { get; set; }

    public DateTime? RegDate { get; set; }

    [StringLength(100)]
    public string? UserName { get; set; }

    /// <summary>
    /// Optional patient photo as a Base64-encoded string (e.g. "data:image/jpeg;base64,...").
    /// Mapped to/from HPatient.PatPix (byte[]).
    /// </summary>
    public string? PatPixBase64 { get; set; }
}
