name: Deploy Aesthetic EMR (Hybrid .NET 10 & Angular 21)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install & Build Angular
        run: |
          cd AestheticEMR/AestheticEMR.client
          npm ci
          npx ng build --configuration production --base-href /emr/

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Publish .NET Backend
        run: dotnet publish AestheticEMR/AestheticEMR.Server/AestheticEMR.Server.csproj --configuration Release --output ./publish

      - name: Web Deploy to SmarterASP.net
        uses: aarhusit/deploy@main
        with:
         # 1. Point it to your server URL secret
         server-url: ${{ secrets.DEPLOY_SERVER_URL }}

         # 2. Append the /emr virtual directory to your site name
         site-name: "omagebi-001-site1/emr"

         # 3. Reference your credentials
         username: ${{ secrets.DEPLOY_USERNAME }}
         password: ${{ secrets.DEPLOY_PASSWORD }}
    
         # 4. Point it to your backend startup project
         csproj-filepath: "AestheticEMR/AestheticEMR.Server/AestheticEMR.Server.csproj"
